In [44]:
"""
Training Instruction:
    - Download the LungHist700 dataset and upload the file into the `digipath/` folder
    - Set the path for `csv_file`, `root_dir`, `load_file` in the `train()` from `digipath/src/train.py` with model configurations
"""

%rm -rf digipath
%rm -rf data

In [38]:
!git clone -b feature https://github.com/chuch3/digipath.git

fatal: destination path 'digipath' already exists and is not an empty directory.

In [43]:
%cd /content
%ls
!unzip LungHist700.zip

/content
digipath/  drive/  LungHist700.zip  sample_data/
Archive:  LungHist700.zip
   creating: data/
   creating: data/LungHist700/
  inflating: data/LungHist700/data.csv
   creating: data/LungHist700/images/
   creating: data/LungHist700/images/aca_md/
  inflating: data/LungHist700/images/aca_md/aca_md_40x_95.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_905.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_73.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_126.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_303.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_301.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_402.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_903.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_85.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_904.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_306.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_83.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_2.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_87.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_82.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_78.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_404.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_60.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_93.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_125.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_305.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_70.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_104.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_302.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_8.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_405.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_96.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_81.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_59.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_404.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_4.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_100.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_86.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_121.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_94.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_101.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_10.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_901.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_124.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_306.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_302.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_88.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_403.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_903.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_92.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_103.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_102.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_80.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_402.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_0.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_401.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_3.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_1.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_122.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_20.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_905.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_304.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_41.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_304.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_97.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_9.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_7.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_305.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_901.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_403.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_75.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_123.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_61.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_90.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_79.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_84.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_77.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_902.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_120.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_5.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_76.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_72.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_63.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_62.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_6.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_303.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_89.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_904.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_401.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_71.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_74.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_91.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_98.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_40x_405.jpg
  inflating: data/LungHist700/images/aca_md/aca_md_20x_902.jpg
   creating: data/LungHist700/images/nor/
  inflating: data/LungHist700/images/nor/nor_40x_11.jpg
  inflating: data/LungHist700/images/nor/nor_40x_404.jpg
  inflating: data/LungHist700/images/nor/nor_40x_16.jpg
  inflating: data/LungHist700/images/nor/nor_20x_5.jpg
  inflating: data/LungHist700/images/nor/nor_20x_403.jpg
  inflating: data/LungHist700/images/nor/nor_20x_51.jpg
  inflating: data/LungHist700/images/nor/nor_20x_32.jpg
  inflating: data/LungHist700/images/nor/nor_20x_301.jpg
  inflating: data/LungHist700/images/nor/nor_40x_13.jpg
  inflating: data/LungHist700/images/nor/nor_20x_304.jpg
  inflating: data/LungHist700/images/nor/nor_20x_48.jpg
  inflating: data/LungHist700/images/nor/nor_40x_89.jpg
  inflating: data/LungHist700/images/nor/nor_40x_80.jpg
  inflating: data/LungHist700/images/nor/nor_20x_66.jpg
  inflating: data/LungHist700/images/nor/nor_40x_402.jpg
  inflating: data/LungHist700/images/nor/nor_20x_904.jpg
  inflating: data/LungHist700/images/nor/nor_20x_25.jpg
  inflating: data/LungHist700/images/nor/nor_40x_3.jpg
  inflating: data/LungHist700/images/nor/nor_40x_97.jpg
  inflating: data/LungHist700/images/nor/nor_40x_304.jpg
  inflating: data/LungHist700/images/nor/nor_40x_29.jpg
  inflating: data/LungHist700/images/nor/nor_20x_13.jpg
  inflating: data/LungHist700/images/nor/nor_40x_901.jpg
  inflating: data/LungHist700/images/nor/nor_20x_10.jpg
  inflating: data/LungHist700/images/nor/nor_20x_905.jpg
  inflating: data/LungHist700/images/nor/nor_40x_6.jpg
  inflating: data/LungHist700/images/nor/nor_20x_33.jpg
  inflating: data/LungHist700/images/nor/nor_20x_34.jpg
  inflating: data/LungHist700/images/nor/nor_40x_86.jpg
  inflating: data/LungHist700/images/nor/nor_20x_6.jpg
  inflating: data/LungHist700/images/nor/nor_20x_38.jpg
  inflating: data/LungHist700/images/nor/nor_20x_36.jpg
  inflating: data/LungHist700/images/nor/nor_40x_28.jpg
  inflating: data/LungHist700/images/nor/nor_40x_18.jpg
  inflating: data/LungHist700/images/nor/nor_20x_303.jpg
  inflating: data/LungHist700/images/nor/nor_20x_68.jpg
  inflating: data/LungHist700/images/nor/nor_20x_31.jpg
  inflating: data/LungHist700/images/nor/nor_40x_93.jpg
  inflating: data/LungHist700/images/nor/nor_40x_20.jpg
  inflating: data/LungHist700/images/nor/nor_20x_305.jpg
  inflating: data/LungHist700/images/nor/nor_20x_27.jpg
  inflating: data/LungHist700/images/nor/nor_40x_94.jpg
  inflating: data/LungHist700/images/nor/nor_20x_903.jpg
  inflating: data/LungHist700/images/nor/nor_20x_3.jpg
  inflating: data/LungHist700/images/nor/nor_40x_82.jpg
  inflating: data/LungHist700/images/nor/nor_40x_19.jpg
  inflating: data/LungHist700/images/nor/nor_40x_96.jpg
  inflating: data/LungHist700/images/nor/nor_20x_72.jpg
  inflating: data/LungHist700/images/nor/nor_40x_25.jpg
  inflating: data/LungHist700/images/nor/nor_40x_305.jpg
  inflating: data/LungHist700/images/nor/nor_40x_24.jpg
  inflating: data/LungHist700/images/nor/nor_20x_44.jpg
  inflating: data/LungHist700/images/nor/nor_20x_70.jpg
  inflating: data/LungHist700/images/nor/nor_40x_100.jpg
  inflating: data/LungHist700/images/nor/nor_20x_60.jpg
  inflating: data/LungHist700/images/nor/nor_20x_901.jpg
  inflating: data/LungHist700/images/nor/nor_20x_402.jpg
  inflating: data/LungHist700/images/nor/nor_40x_303.jpg
  inflating: data/LungHist700/images/nor/nor_40x_8.jpg
  inflating: data/LungHist700/images/nor/nor_20x_39.jpg
  inflating: data/LungHist700/images/nor/nor_20x_22.jpg
  inflating: data/LungHist700/images/nor/nor_20x_35.jpg
  inflating: data/LungHist700/images/nor/nor_40x_5.jpg
  inflating: data/LungHist700/images/nor/nor_20x_12.jpg
  inflating: data/LungHist700/images/nor/nor_20x_53.jpg
  inflating: data/LungHist700/images/nor/nor_40x_23.jpg
  inflating: data/LungHist700/images/nor/nor_20x_9.jpg
  inflating: data/LungHist700/images/nor/nor_40x_81.jpg
  inflating: data/LungHist700/images/nor/nor_20x_71.jpg
  inflating: data/LungHist700/images/nor/nor_20x_62.jpg
  inflating: data/LungHist700/images/nor/nor_20x_42.jpg
  inflating: data/LungHist700/images/nor/nor_20x_43.jpg
  inflating: data/LungHist700/images/nor/nor_20x_45.jpg
  inflating: data/LungHist700/images/nor/nor_20x_26.jpg
  inflating: data/LungHist700/images/nor/nor_40x_4.jpg
  inflating: data/LungHist700/images/nor/nor_20x_401.jpg
  inflating: data/LungHist700/images/nor/nor_40x_10.jpg
  inflating: data/LungHist700/images/nor/nor_40x_91.jpg
  inflating: data/LungHist700/images/nor/nor_20x_69.jpg
  inflating: data/LungHist700/images/nor/nor_20x_404.jpg
  inflating: data/LungHist700/images/nor/nor_40x_12.jpg
  inflating: data/LungHist700/images/nor/nor_20x_2.jpg
  inflating: data/LungHist700/images/nor/nor_20x_21.jpg
  inflating: data/LungHist700/images/nor/nor_40x_87.jpg
  inflating: data/LungHist700/images/nor/nor_20x_56.jpg
  inflating: data/LungHist700/images/nor/nor_20x_50.jpg
  inflating: data/LungHist700/images/nor/nor_20x_1.jpg
  inflating: data/LungHist700/images/nor/nor_20x_902.jpg
  inflating: data/LungHist700/images/nor/nor_20x_14.jpg
  inflating: data/LungHist700/images/nor/nor_20x_61.jpg
  inflating: data/LungHist700/images/nor/nor_20x_15.jpg
  inflating: data/LungHist700/images/nor/nor_20x_49.jpg
  inflating: data/LungHist700/images/nor/nor_20x_23.jpg
  inflating: data/LungHist700/images/nor/nor_20x_57.jpg
  inflating: data/LungHist700/images/nor/nor_40x_85.jpg
  inflating: data/LungHist700/images/nor/nor_40x_21.jpg
  inflating: data/LungHist700/images/nor/nor_20x_8.jpg
  inflating: data/LungHist700/images/nor/nor_20x_11.jpg
  inflating: data/LungHist700/images/nor/nor_40x_30.jpg
  inflating: data/LungHist700/images/nor/nor_40x_905.jpg
  inflating: data/LungHist700/images/nor/nor_20x_16.jpg
  inflating: data/LungHist700/images/nor/nor_20x_302.jpg
  inflating: data/LungHist700/images/nor/nor_40x_7.jpg
  inflating: data/LungHist700/images/nor/nor_20x_20.jpg
  inflating: data/LungHist700/images/nor/nor_20x_67.jpg
  inflating: data/LungHist700/images/nor/nor_20x_40.jpg
  inflating: data/LungHist700/images/nor/nor_40x_95.jpg
  inflating: data/LungHist700/images/nor/nor_40x_302.jpg
  inflating: data/LungHist700/images/nor/nor_40x_90.jpg
  inflating: data/LungHist700/images/nor/nor_40x_14.jpg
  inflating: data/LungHist700/images/nor/nor_40x_84.jpg
  inflating: data/LungHist700/images/nor/nor_40x_26.jpg
  inflating: data/LungHist700/images/nor/nor_40x_27.jpg
  inflating: data/LungHist700/images/nor/nor_20x_59.jpg
  inflating: data/LungHist700/images/nor/nor_40x_301.jpg
  inflating: data/LungHist700/images/nor/nor_20x_4.jpg
  inflating: data/LungHist700/images/nor/nor_40x_88.jpg
  inflating: data/LungHist700/images/nor/nor_20x_41.jpg
  inflating: data/LungHist700/images/nor/nor_20x_19.jpg
  inflating: data/LungHist700/images/nor/nor_40x_99.jpg
  inflating: data/LungHist700/images/nor/nor_40x_22.jpg
  inflating: data/LungHist700/images/nor/nor_40x_9.jpg
  inflating: data/LungHist700/images/nor/nor_40x_83.jpg
  inflating: data/LungHist700/images/nor/nor_40x_98.jpg
  inflating: data/LungHist700/images/nor/nor_40x_902.jpg
  inflating: data/LungHist700/images/nor/nor_40x_904.jpg
  inflating: data/LungHist700/images/nor/nor_20x_37.jpg
  inflating: data/LungHist700/images/nor/nor_20x_58.jpg
  inflating: data/LungHist700/images/nor/nor_20x_52.jpg
  inflating: data/LungHist700/images/nor/nor_20x_54.jpg
  inflating: data/LungHist700/images/nor/nor_20x_29.jpg
  inflating: data/LungHist700/images/nor/nor_40x_15.jpg
  inflating: data/LungHist700/images/nor/nor_20x_64.jpg
  inflating: data/LungHist700/images/nor/nor_20x_63.jpg
  inflating: data/LungHist700/images/nor/nor_20x_28.jpg
  inflating: data/LungHist700/images/nor/nor_20x_7.jpg
  inflating: data/LungHist700/images/nor/nor_40x_1.jpg
  inflating: data/LungHist700/images/nor/nor_40x_403.jpg
  inflating: data/LungHist700/images/nor/nor_40x_92.jpg
  inflating: data/LungHist700/images/nor/nor_20x_47.jpg
  inflating: data/LungHist700/images/nor/nor_40x_17.jpg
  inflating: data/LungHist700/images/nor/nor_40x_101.jpg
  inflating: data/LungHist700/images/nor/nor_40x_903.jpg
  inflating: data/LungHist700/images/nor/nor_20x_17.jpg
  inflating: data/LungHist700/images/nor/nor_20x_55.jpg
  inflating: data/LungHist700/images/nor/nor_40x_2.jpg
  inflating: data/LungHist700/images/nor/nor_20x_18.jpg
  inflating: data/LungHist700/images/nor/nor_20x_30.jpg
  inflating: data/LungHist700/images/nor/nor_20x_65.jpg
  inflating: data/LungHist700/images/nor/nor_40x_401.jpg
  inflating: data/LungHist700/images/nor/nor_20x_24.jpg
   creating: data/LungHist700/images/scc_md/
  inflating: data/LungHist700/images/scc_md/scc_md_40x_902.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_405.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_25.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_404.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_52.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_71.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_22.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_401.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_33.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_901.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_62.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_60.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_65.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_66.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_35.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_51.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_901.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_301.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_23.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_403.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_903.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_55.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_24.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_68.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_29.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_34.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_304.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_64.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_28.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_404.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_905.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_905.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_303.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_73.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_54.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_69.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_304.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_405.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_72.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_401.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_63.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_904.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_305.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_61.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_201.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_302.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_54.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_403.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_303.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_74.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_53.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_301.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_402.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_903.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_70.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_26.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_402.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_52.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_6.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_305.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_4.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_53.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_902.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_302.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_20x_904.jpg
  inflating: data/LungHist700/images/scc_md/scc_md_40x_67.jpg
   creating: data/LungHist700/images/scc_bd/
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_83.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_905.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_74.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_32.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_46.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_403.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_36.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_903.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_82.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_303.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_404.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_902.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_37.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_46.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_5.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_84.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_40x_28.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_71.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_301.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_402.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_904.jpg
  inflating: data/LungHist700/images/scc_bd/scc_bd_20x_901.jpg

In [23]:
%mv data/ digipath/

In [41]:
%cd digipath/src/
os.getcwd()

/content/digipath/src

'/content/digipath/src'

In [42]:
!git pull

Already up to date.

In [2]:
import os
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import rich
import torch
import torch.nn as nn
import torchvision
from matplotlib.pyplot import imshow
from PIL import Image
from rich.panel import Panel
from sklearn.model_selection import GroupShuffleSplit
from torch.optim import Adam
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader, Dataset, TensorDataset
from torchvision import transforms
from torchvision.models import ViT_B_16_Weights
from tqdm import tqdm

from constant import (
    LUNG_IMAGES_DIR,
    LUNG_LOADED_FILE,
    LUNG_METADATA_FILE,
    LUNG_MODEL_DIR,
    LUNG_PREPROCESS_DIR,
    SSL_CHECKPOINT,
)
from dataset import load_dataset
from extract import extract_embeddings
from macenko import build_macenko_normalizer
from model import ClassifierHead
from ssl_train import pretrain_ssl
from transform import det_transform, rand_transform

In [6]:
csv_file = LUNG_METADATA_FILE
meta = pd.read_csv(csv_file)
meta

    superclass subclass resolution  image_id  patient_id
0          aca       bd        40x       901           1
1          aca       bd        40x       902           1
2          aca       bd        40x       903           1
3          aca       bd        40x       904           1
4          aca       bd        40x       905           1
..         ...      ...        ...       ...         ...
686        nor      NaN        20x       901          45
687        nor      NaN        20x       902          45
688        nor      NaN        20x       903          45
689        nor      NaN        20x       904          45
690        nor      NaN        20x       905          45

[691 rows x 5 columns]

In [9]:
meta.info()

<class 'pandas.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   superclass  691 non-null    str
 1   subclass    540 non-null    str
 2   resolution  691 non-null    str
 3   image_id    691 non-null    int64
 4   patient_id  691 non-null    int64
dtypes: int64(2), str(3)
memory usage: 27.1 KB

In [27]:
meta[['superclass', 'subclass', 'resolution']].value_counts()

superclass  subclass  resolution
aca         bd        20x           57
scc         bd        20x           50
                      40x           49
            pd        20x           48
                      40x           47
aca         bd        40x           46
            md        40x           46
            pd        20x           45
            md        20x           44
            pd        40x           42
scc         md        40x           36
                      20x           30
Name: count, dtype: int64

In [26]:
meta['subclass'].value_counts()

subclass
bd    202
pd    182
md    156
Name: count, dtype: int64

In [10]:
meta.isnull().sum()

superclass      0
subclass      151
resolution      0
image_id        0
patient_id      0
dtype: int64

In [15]:
meta[meta['superclass'] == 'nor'][['superclass', 'subclass']].head()

    superclass subclass
540        nor      NaN
541        nor      NaN
542        nor      NaN
543        nor      NaN
544        nor      NaN

In [11]:
meta['resolution'].unique()

<StringArray>
['40x', '20x']
Length: 2, dtype: str

In [19]:
load_file=LUNG_LOADED_FILE
load_meta = pd.read_csv(load_file)
load_meta

                                                  path  label  patient_id
0    /home/chu/dev/wsi-grading/data/LungHist700/ima...      1          16
1    /home/chu/dev/wsi-grading/data/LungHist700/ima...      1           2
2    /home/chu/dev/wsi-grading/data/LungHist700/ima...      1          16
3    /home/chu/dev/wsi-grading/data/LungHist700/ima...      1          15
4    /home/chu/dev/wsi-grading/data/LungHist700/ima...      1          12
..                                                 ...    ...         ...
686  /home/chu/dev/wsi-grading/data/LungHist700/ima...      0           7
687  /home/chu/dev/wsi-grading/data/LungHist700/ima...      0          10
688  /home/chu/dev/wsi-grading/data/LungHist700/ima...      0           6
689  /home/chu/dev/wsi-grading/data/LungHist700/ima...      0          12
690  /home/chu/dev/wsi-grading/data/LungHist700/ima...      0           7

[691 rows x 3 columns]

In [21]:
load_meta['path'][0]

'/home/chu/dev/wsi-grading/data/LungHist700/images/aca_md/aca_md_40x_95.jpg'

In [1]:
from training import train
train()

=> Using device : cpu
=> Metadata file : `/home/chu/dev/wsi-grading/data/LungHist700/data.csv`
=> Root directory : `/home/chu/dev/wsi-grading/data/LungHist700/images`

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ LungHist700 Target Label Statistics                                                                             │
│ ----------                                                                                                      │
│ Label map: {'aca_bd': 0, 'aca_md': 1, 'aca_pd': 2, 'scc_bd': 3, 'scc_md': 4, 'scc_pd': 5, 'nor': 6}             │
│                                                                                                                 │
│ label                                                                                                           │
│ 6    151                                                                                                        │
│ 0    103                                                                                                        │
│ 3     99                                                                                                        │
│ 5     95                                                                                                        │
│ 1     90                                                                                                        │
│ 2     87                                                                                                        │
│ 4     66                                                                                                        │
│ Name: count, dtype: int64                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ LungHist700 Dataset Split Statistics (Patient-Level)                                                            │
│ ----------                                                                                                      │
│ Train split : 71.3459%                                                                                          │
│ Validation splt : 16.6425%                                                                                      │
│ Test splt : 12.0116%                                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

=> Checking if loaded dataset exists.
=> Loaded dataset already exists, continuing process.
=> Loading cached embeddings from /home/chu/dev/wsi-grading/preprocess/lung_embedded_stain_ssl.pt

> Training~ :   1%|█▏                                                                                                                   | 2/200 [00:00<00:28,  6.90it/s]

 Epochs 001 | Train loss : 1.94 | Train acc 19.68 % | Val loss 1.8226 | Val acc 46.99%
 Epochs 002 | Train loss : 1.87 | Train acc 26.77 % | Val loss 1.6631 | Val acc 55.42%

> Training~ :   2%|██▎                                                                                                                  | 4/200 [00:00<00:23,  8.49it/s]

 Epochs 003 | Train loss : 1.83 | Train acc 29.82 % | Val loss 1.5654 | Val acc 56.63%
 Epochs 004 | Train loss : 1.80 | Train acc 30.83 % | Val loss 1.4982 | Val acc 56.63%

> Training~ :   3%|███▌                                                                                                                 | 6/200 [00:00<00:21,  8.99it/s]

 Epochs 005 | Train loss : 1.75 | Train acc 33.27 % | Val loss 1.4545 | Val acc 55.42%
 Epochs 006 | Train loss : 1.72 | Train acc 34.28 % | Val loss 1.4035 | Val acc 56.63%

> Training~ :   4%|████▋                                                                                                                | 8/200 [00:00<00:20,  9.29it/s]

 Epochs 007 | Train loss : 1.69 | Train acc 36.31 % | Val loss 1.3888 | Val acc 57.83%
 Epochs 008 | Train loss : 1.67 | Train acc 36.71 % | Val loss 1.3628 | Val acc 60.24%

> Training~ :   5%|█████▊                                                                                                              | 10/200 [00:01<00:20,  9.47it/s]

 Epochs 009 | Train loss : 1.64 | Train acc 37.32 % | Val loss 1.3531 | Val acc 61.45%
 Epochs 010 | Train loss : 1.62 | Train acc 39.15 % | Val loss 1.3186 | Val acc 62.65%

> Training~ :   6%|██████▉                                                                                                             | 12/200 [00:01<00:19,  9.59it/s]

 Epochs 011 | Train loss : 1.57 | Train acc 39.96 % | Val loss 1.3059 | Val acc 61.45%
 Epochs 012 | Train loss : 1.56 | Train acc 42.39 % | Val loss 1.2713 | Val acc 68.67%
 Epochs 013 | Train loss : 1.52 | Train acc 45.23 % | Val loss 1.2582 | Val acc 68.67%

> Training~ :   8%|█████████▎                                                                                                          | 16/200 [00:01<00:17, 10.49it/s]

 Epochs 014 | Train loss : 1.50 | Train acc 45.64 % | Val loss 1.2532 | Val acc 67.47%
 Epochs 015 | Train loss : 1.49 | Train acc 46.04 % | Val loss 1.2292 | Val acc 66.27%
 Epochs 016 | Train loss : 1.45 | Train acc 50.51 % | Val loss 1.2232 | Val acc 68.67%

> Training~ :   9%|██████████▍                                                                                                         | 18/200 [00:01<00:17, 10.17it/s]

 Epochs 017 | Train loss : 1.43 | Train acc 48.48 % | Val loss 1.2239 | Val acc 66.27%
 Epochs 018 | Train loss : 1.41 | Train acc 48.88 % | Val loss 1.2161 | Val acc 71.08%
 Epochs 019 | Train loss : 1.39 | Train acc 53.35 % | Val loss 1.1696 | Val acc 72.29%

> Training~ :  11%|████████████▊                                                                                                       | 22/200 [00:02<00:17, 10.17it/s]

 Epochs 020 | Train loss : 1.36 | Train acc 53.55 % | Val loss 1.1561 | Val acc 73.49%
 Epochs 021 | Train loss : 1.35 | Train acc 52.74 % | Val loss 1.1473 | Val acc 71.08%
 Epochs 022 | Train loss : 1.32 | Train acc 54.77 % | Val loss 1.1378 | Val acc 73.49%

> Training~ :  12%|█████████████▉                                                                                                      | 24/200 [00:02<00:17, 10.08it/s]

 Epochs 023 | Train loss : 1.31 | Train acc 52.33 % | Val loss 1.1468 | Val acc 73.49%
 Epochs 024 | Train loss : 1.29 | Train acc 55.17 % | Val loss 1.1225 | Val acc 74.70%
 Epochs 025 | Train loss : 1.27 | Train acc 57.61 % | Val loss 1.1047 | Val acc 74.70%

> Training~ :  13%|███████████████                                                                                                     | 26/200 [00:02<00:17, 10.03it/s]

 Epochs 026 | Train loss : 1.25 | Train acc 60.04 % | Val loss 1.0902 | Val acc 74.70%
 Epochs 027 | Train loss : 1.25 | Train acc 59.23 % | Val loss 1.0812 | Val acc 73.49%

> Training~ :  14%|████████████████▊                                                                                                   | 29/200 [00:03<00:17,  9.77it/s]

 Epochs 028 | Train loss : 1.23 | Train acc 58.42 % | Val loss 1.0546 | Val acc 74.70%
 Epochs 029 | Train loss : 1.21 | Train acc 60.45 % | Val loss 1.0604 | Val acc 74.70%

> Training~ :  16%|█████████████████▉                                                                                                  | 31/200 [00:03<00:17,  9.79it/s]

 Epochs 030 | Train loss : 1.21 | Train acc 58.22 % | Val loss 1.0565 | Val acc 73.49%
 Epochs 031 | Train loss : 1.19 | Train acc 58.42 % | Val loss 1.0578 | Val acc 73.49%
 Epochs 032 | Train loss : 1.16 | Train acc 60.85 % | Val loss 1.0378 | Val acc 73.49%

> Training~ :  17%|███████████████████▋                                                                                                | 34/200 [00:03<00:16,  9.88it/s]

 Epochs 033 | Train loss : 1.17 | Train acc 61.26 % | Val loss 1.0530 | Val acc 73.49%
 Epochs 034 | Train loss : 1.17 | Train acc 59.23 % | Val loss 1.0267 | Val acc 73.49%

> Training~ :  18%|████████████████████▉                                                                                               | 36/200 [00:03<00:16,  9.76it/s]

 Epochs 035 | Train loss : 1.16 | Train acc 61.87 % | Val loss 1.0199 | Val acc 73.49%
 Epochs 036 | Train loss : 1.15 | Train acc 61.87 % | Val loss 0.9932 | Val acc 74.70%

> Training~ :  19%|██████████████████████                                                                                              | 38/200 [00:03<00:18,  8.79it/s]

 Epochs 037 | Train loss : 1.13 | Train acc 61.66 % | Val loss 1.0066 | Val acc 73.49%
 Epochs 038 | Train loss : 1.11 | Train acc 61.66 % | Val loss 0.9795 | Val acc 75.90%

> Training~ :  20%|███████████████████████▏                                                                                            | 40/200 [00:04<00:18,  8.74it/s]

 Epochs 039 | Train loss : 1.10 | Train acc 62.88 % | Val loss 0.9910 | Val acc 72.29%
 Epochs 040 | Train loss : 1.10 | Train acc 61.87 % | Val loss 0.9746 | Val acc 72.29%

> Training~ :  21%|████████████████████████▎                                                                                           | 42/200 [00:04<00:17,  9.08it/s]

 Epochs 041 | Train loss : 1.11 | Train acc 65.72 % | Val loss 0.9682 | Val acc 73.49%
 Epochs 042 | Train loss : 1.06 | Train acc 64.71 % | Val loss 0.9669 | Val acc 74.70%

> Training~ :  22%|█████████████████████████▌                                                                                          | 44/200 [00:04<00:17,  9.13it/s]

 Epochs 043 | Train loss : 1.08 | Train acc 64.10 % | Val loss 0.9637 | Val acc 73.49%
 Epochs 044 | Train loss : 1.08 | Train acc 63.29 % | Val loss 0.9631 | Val acc 75.90%

> Training~ :  23%|██████████████████████████▋                                                                                         | 46/200 [00:04<00:17,  8.99it/s]

 Epochs 045 | Train loss : 1.09 | Train acc 64.50 % | Val loss 0.9479 | Val acc 75.90%
 Epochs 046 | Train loss : 1.06 | Train acc 65.31 % | Val loss 0.9492 | Val acc 75.90%

> Training~ :  24%|███████████████████████████▊                                                                                        | 48/200 [00:05<00:19,  7.65it/s]

 Epochs 047 | Train loss : 1.05 | Train acc 63.69 % | Val loss 0.9345 | Val acc 74.70%
 Epochs 048 | Train loss : 1.04 | Train acc 64.10 % | Val loss 0.9361 | Val acc 75.90%

> Training~ :  25%|█████████████████████████████                                                                                       | 50/200 [00:05<00:21,  7.08it/s]

 Epochs 049 | Train loss : 1.04 | Train acc 64.10 % | Val loss 0.9281 | Val acc 75.90%
 Epochs 050 | Train loss : 1.00 | Train acc 67.14 % | Val loss 0.9192 | Val acc 75.90%

> Training~ :  26%|██████████████████████████████▏                                                                                     | 52/200 [00:05<00:21,  6.95it/s]

 Epochs 051 | Train loss : 1.01 | Train acc 68.15 % | Val loss 0.9188 | Val acc 74.70%
 Epochs 052 | Train loss : 1.00 | Train acc 63.29 % | Val loss 0.9024 | Val acc 74.70%

> Training~ :  27%|███████████████████████████████▎                                                                                    | 54/200 [00:06<00:21,  6.64it/s]

 Epochs 053 | Train loss : 1.01 | Train acc 65.72 % | Val loss 0.8908 | Val acc 74.70%
 Epochs 054 | Train loss : 1.00 | Train acc 67.34 % | Val loss 0.9083 | Val acc 74.70%

> Training~ :  28%|████████████████████████████████▍                                                                                   | 56/200 [00:06<00:20,  6.87it/s]

 Epochs 055 | Train loss : 1.00 | Train acc 67.34 % | Val loss 0.9180 | Val acc 75.90%
 Epochs 056 | Train loss : 0.98 | Train acc 67.75 % | Val loss 0.8918 | Val acc 74.70%

> Training~ :  30%|██████████████████████████████████▏                                                                                 | 59/200 [00:06<00:16,  8.55it/s]

 Epochs 057 | Train loss : 0.97 | Train acc 67.55 % | Val loss 0.8757 | Val acc 74.70%
 Epochs 058 | Train loss : 0.97 | Train acc 70.18 % | Val loss 0.8749 | Val acc 74.70%
 Epochs 059 | Train loss : 0.98 | Train acc 67.95 % | Val loss 0.8819 | Val acc 74.70%

> Training~ :  30%|███████████████████████████████████▍                                                                                | 61/200 [00:06<00:17,  8.08it/s]

 Epochs 060 | Train loss : 0.97 | Train acc 67.34 % | Val loss 0.8886 | Val acc 74.70%
 Epochs 061 | Train loss : 0.96 | Train acc 67.34 % | Val loss 0.8781 | Val acc 74.70%

> Training~ :  32%|████████████████████████████████████▌                                                                               | 63/200 [00:07<00:17,  7.99it/s]

 Epochs 062 | Train loss : 0.96 | Train acc 67.75 % | Val loss 0.8653 | Val acc 74.70%
 Epochs 063 | Train loss : 0.95 | Train acc 68.56 % | Val loss 0.8799 | Val acc 74.70%

> Training~ :  32%|█████████████████████████████████████▋                                                                              | 65/200 [00:07<00:15,  8.61it/s]

 Epochs 064 | Train loss : 0.95 | Train acc 67.75 % | Val loss 0.8719 | Val acc 74.70%
 Epochs 065 | Train loss : 0.94 | Train acc 68.97 % | Val loss 0.8692 | Val acc 74.70%

> Training~ :  34%|██████████████████████████████████████▊                                                                             | 67/200 [00:07<00:15,  8.82it/s]

 Epochs 066 | Train loss : 0.93 | Train acc 69.37 % | Val loss 0.8698 | Val acc 74.70%
 Epochs 067 | Train loss : 0.94 | Train acc 70.59 % | Val loss 0.8513 | Val acc 74.70%

> Training~ :  34%|████████████████████████████████████████                                                                            | 69/200 [00:07<00:15,  8.31it/s]

 Epochs 068 | Train loss : 0.92 | Train acc 69.98 % | Val loss 0.8371 | Val acc 74.70%
 Epochs 069 | Train loss : 0.93 | Train acc 68.15 % | Val loss 0.8477 | Val acc 74.70%

> Training~ :  36%|█████████████████████████████████████████▏                                                                          | 71/200 [00:08<00:14,  8.95it/s]

 Epochs 070 | Train loss : 0.92 | Train acc 67.34 % | Val loss 0.8422 | Val acc 74.70%
 Epochs 071 | Train loss : 0.91 | Train acc 69.57 % | Val loss 0.8469 | Val acc 74.70%

> Training~ :  36%|██████████████████████████████████████████▎                                                                         | 73/200 [00:08<00:14,  8.76it/s]

 Epochs 072 | Train loss : 0.89 | Train acc 70.79 % | Val loss 0.8356 | Val acc 74.70%
 Epochs 073 | Train loss : 0.90 | Train acc 72.41 % | Val loss 0.8136 | Val acc 74.70%

> Training~ :  38%|███████████████████████████████████████████▌                                                                        | 75/200 [00:08<00:14,  8.74it/s]

 Epochs 074 | Train loss : 0.89 | Train acc 69.98 % | Val loss 0.8155 | Val acc 75.90%
 Epochs 075 | Train loss : 0.90 | Train acc 69.37 % | Val loss 0.8416 | Val acc 74.70%

> Training~ :  38%|████████████████████████████████████████████▋                                                                       | 77/200 [00:08<00:13,  9.06it/s]

 Epochs 076 | Train loss : 0.89 | Train acc 69.98 % | Val loss 0.8396 | Val acc 74.70%
 Epochs 077 | Train loss : 0.88 | Train acc 70.59 % | Val loss 0.8041 | Val acc 75.90%

> Training~ :  40%|█████████████████████████████████████████████▊                                                                      | 79/200 [00:08<00:13,  9.02it/s]

 Epochs 078 | Train loss : 0.88 | Train acc 70.99 % | Val loss 0.8060 | Val acc 75.90%
 Epochs 079 | Train loss : 0.86 | Train acc 73.23 % | Val loss 0.8080 | Val acc 77.11%

> Training~ :  41%|███████████████████████████████████████████████▌                                                                    | 82/200 [00:09<00:12,  9.59it/s]

 Epochs 080 | Train loss : 0.89 | Train acc 68.76 % | Val loss 0.8170 | Val acc 77.11%
 Epochs 081 | Train loss : 0.85 | Train acc 72.01 % | Val loss 0.7946 | Val acc 77.11%
 Epochs 082 | Train loss : 0.85 | Train acc 72.21 % | Val loss 0.8075 | Val acc 75.90%

> Training~ :  42%|████████████████████████████████████████████████▋                                                                   | 84/200 [00:09<00:13,  8.69it/s]

 Epochs 083 | Train loss : 0.85 | Train acc 72.01 % | Val loss 0.8158 | Val acc 77.11%
 Epochs 084 | Train loss : 0.85 | Train acc 71.40 % | Val loss 0.7877 | Val acc 77.11%

> Training~ :  43%|█████████████████████████████████████████████████▉                                                                  | 86/200 [00:09<00:13,  8.65it/s]

 Epochs 085 | Train loss : 0.84 | Train acc 72.82 % | Val loss 0.8020 | Val acc 77.11%
 Epochs 086 | Train loss : 0.86 | Train acc 71.60 % | Val loss 0.7894 | Val acc 77.11%

> Training~ :  44%|███████████████████████████████████████████████████                                                                 | 88/200 [00:10<00:13,  8.15it/s]

 Epochs 087 | Train loss : 0.84 | Train acc 71.81 % | Val loss 0.7810 | Val acc 77.11%
 Epochs 088 | Train loss : 0.85 | Train acc 72.01 % | Val loss 0.8058 | Val acc 77.11%

> Training~ :  45%|████████████████████████████████████████████████████▏                                                               | 90/200 [00:10<00:13,  7.90it/s]

 Epochs 089 | Train loss : 0.86 | Train acc 71.20 % | Val loss 0.7895 | Val acc 77.11%
 Epochs 090 | Train loss : 0.83 | Train acc 71.81 % | Val loss 0.7777 | Val acc 78.31%

> Training~ :  46%|█████████████████████████████████████████████████████▎                                                              | 92/200 [00:10<00:13,  8.24it/s]

 Epochs 091 | Train loss : 0.84 | Train acc 70.79 % | Val loss 0.7646 | Val acc 79.52%
 Epochs 092 | Train loss : 0.83 | Train acc 71.60 % | Val loss 0.7841 | Val acc 77.11%

> Training~ :  47%|██████████████████████████████████████████████████████▌                                                             | 94/200 [00:10<00:12,  8.68it/s]

 Epochs 093 | Train loss : 0.84 | Train acc 72.41 % | Val loss 0.7852 | Val acc 77.11%
 Epochs 094 | Train loss : 0.83 | Train acc 73.02 % | Val loss 0.7642 | Val acc 79.52%

> Training~ :  48%|███████████████████████████████████████████████████████▋                                                            | 96/200 [00:11<00:13,  7.91it/s]

 Epochs 095 | Train loss : 0.82 | Train acc 70.99 % | Val loss 0.7809 | Val acc 78.31%
 Epochs 096 | Train loss : 0.83 | Train acc 72.62 % | Val loss 0.7641 | Val acc 77.11%

> Training~ :  49%|████████████████████████████████████████████████████████▊                                                           | 98/200 [00:11<00:14,  6.99it/s]

 Epochs 097 | Train loss : 0.82 | Train acc 72.41 % | Val loss 0.7567 | Val acc 79.52%
 Epochs 098 | Train loss : 0.80 | Train acc 73.43 % | Val loss 0.7527 | Val acc 78.31%

> Training~ :  50%|█████████████████████████████████████████████████████████▌                                                         | 100/200 [00:11<00:15,  6.45it/s]

 Epochs 099 | Train loss : 0.81 | Train acc 72.82 % | Val loss 0.7703 | Val acc 78.31%
 Epochs 100 | Train loss : 0.83 | Train acc 74.04 % | Val loss 0.7454 | Val acc 78.31%

> Training~ :  51%|██████████████████████████████████████████████████████████▋                                                        | 102/200 [00:12<00:16,  6.07it/s]

 Epochs 101 | Train loss : 0.82 | Train acc 73.02 % | Val loss 0.7560 | Val acc 77.11%
 Epochs 102 | Train loss : 0.81 | Train acc 71.60 % | Val loss 0.7652 | Val acc 79.52%

> Training~ :  52%|███████████████████████████████████████████████████████████▊                                                       | 104/200 [00:12<00:15,  6.13it/s]

 Epochs 103 | Train loss : 0.78 | Train acc 74.04 % | Val loss 0.7498 | Val acc 79.52%
 Epochs 104 | Train loss : 0.79 | Train acc 74.65 % | Val loss 0.7430 | Val acc 79.52%

> Training~ :  53%|████████████████████████████████████████████████████████████▉                                                      | 106/200 [00:12<00:15,  6.14it/s]

 Epochs 105 | Train loss : 0.79 | Train acc 75.66 % | Val loss 0.7452 | Val acc 79.52%
 Epochs 106 | Train loss : 0.76 | Train acc 74.65 % | Val loss 0.7325 | Val acc 79.52%

> Training~ :  54%|██████████████████████████████████████████████████████████████                                                     | 108/200 [00:13<00:15,  6.05it/s]

 Epochs 107 | Train loss : 0.78 | Train acc 74.04 % | Val loss 0.7558 | Val acc 79.52%
 Epochs 108 | Train loss : 0.79 | Train acc 75.46 % | Val loss 0.7299 | Val acc 78.31%

> Training~ :  55%|███████████████████████████████████████████████████████████████▎                                                   | 110/200 [00:13<00:14,  6.21it/s]

 Epochs 109 | Train loss : 0.78 | Train acc 73.63 % | Val loss 0.7345 | Val acc 79.52%
 Epochs 110 | Train loss : 0.76 | Train acc 74.65 % | Val loss 0.7415 | Val acc 79.52%

> Training~ :  56%|████████████████████████████████████████████████████████████████▍                                                  | 112/200 [00:13<00:14,  6.17it/s]

 Epochs 111 | Train loss : 0.77 | Train acc 75.05 % | Val loss 0.7282 | Val acc 79.52%
 Epochs 112 | Train loss : 0.78 | Train acc 73.83 % | Val loss 0.7399 | Val acc 79.52%

> Training~ :  57%|█████████████████████████████████████████████████████████████████▌                                                 | 114/200 [00:13<00:14,  6.02it/s]

 Epochs 113 | Train loss : 0.76 | Train acc 74.04 % | Val loss 0.7248 | Val acc 79.52%
 Epochs 114 | Train loss : 0.77 | Train acc 76.27 % | Val loss 0.7249 | Val acc 78.31%

> Training~ :  58%|██████████████████████████████████████████████████████████████████▋                                                | 116/200 [00:14<00:14,  5.95it/s]

 Epochs 115 | Train loss : 0.75 | Train acc 75.66 % | Val loss 0.7276 | Val acc 79.52%
 Epochs 116 | Train loss : 0.76 | Train acc 75.86 % | Val loss 0.7270 | Val acc 79.52%

> Training~ :  59%|███████████████████████████████████████████████████████████████████▊                                               | 118/200 [00:14<00:13,  6.20it/s]

 Epochs 117 | Train loss : 0.75 | Train acc 75.46 % | Val loss 0.7315 | Val acc 79.52%
 Epochs 118 | Train loss : 0.75 | Train acc 74.44 % | Val loss 0.7222 | Val acc 78.31%

> Training~ :  60%|█████████████████████████████████████████████████████████████████████                                              | 120/200 [00:14<00:12,  6.47it/s]

 Epochs 119 | Train loss : 0.75 | Train acc 74.85 % | Val loss 0.7252 | Val acc 79.52%
 Epochs 120 | Train loss : 0.76 | Train acc 75.46 % | Val loss 0.7105 | Val acc 79.52%

> Training~ :  61%|██████████████████████████████████████████████████████████████████████▏                                            | 122/200 [00:15<00:11,  6.54it/s]

 Epochs 121 | Train loss : 0.75 | Train acc 73.43 % | Val loss 0.7141 | Val acc 79.52%
 Epochs 122 | Train loss : 0.73 | Train acc 75.86 % | Val loss 0.7130 | Val acc 79.52%

> Training~ :  62%|███████████████████████████████████████████████████████████████████████▎                                           | 124/200 [00:15<00:11,  6.40it/s]

 Epochs 123 | Train loss : 0.73 | Train acc 77.28 % | Val loss 0.7293 | Val acc 79.52%
 Epochs 124 | Train loss : 0.74 | Train acc 77.28 % | Val loss 0.7092 | Val acc 79.52%

> Training~ :  63%|████████████████████████████████████████████████████████████████████████▍                                          | 126/200 [00:15<00:11,  6.34it/s]

 Epochs 125 | Train loss : 0.75 | Train acc 75.46 % | Val loss 0.7098 | Val acc 79.52%
 Epochs 126 | Train loss : 0.72 | Train acc 75.46 % | Val loss 0.7034 | Val acc 79.52%

> Training~ :  64%|█████████████████████████████████████████████████████████████████████████▌                                         | 128/200 [00:16<00:11,  6.29it/s]

 Epochs 127 | Train loss : 0.73 | Train acc 75.25 % | Val loss 0.6869 | Val acc 79.52%
 Epochs 128 | Train loss : 0.73 | Train acc 77.69 % | Val loss 0.6871 | Val acc 79.52%

> Training~ :  65%|██████████████████████████████████████████████████████████████████████████▊                                        | 130/200 [00:16<00:11,  5.98it/s]

 Epochs 129 | Train loss : 0.71 | Train acc 76.88 % | Val loss 0.6794 | Val acc 79.52%
 Epochs 130 | Train loss : 0.73 | Train acc 75.66 % | Val loss 0.6914 | Val acc 79.52%

> Training~ :  66%|███████████████████████████████████████████████████████████████████████████▉                                       | 132/200 [00:16<00:11,  5.94it/s]

 Epochs 131 | Train loss : 0.71 | Train acc 76.67 % | Val loss 0.6865 | Val acc 79.52%
 Epochs 132 | Train loss : 0.71 | Train acc 77.08 % | Val loss 0.6902 | Val acc 79.52%

> Training~ :  67%|█████████████████████████████████████████████████████████████████████████████                                      | 134/200 [00:17<00:10,  6.12it/s]

 Epochs 133 | Train loss : 0.71 | Train acc 78.50 % | Val loss 0.6770 | Val acc 79.52%
 Epochs 134 | Train loss : 0.72 | Train acc 74.85 % | Val loss 0.6907 | Val acc 79.52%

> Training~ :  68%|██████████████████████████████████████████████████████████████████████████████▏                                    | 136/200 [00:17<00:10,  6.16it/s]

 Epochs 135 | Train loss : 0.72 | Train acc 76.27 % | Val loss 0.6776 | Val acc 79.52%
 Epochs 136 | Train loss : 0.71 | Train acc 76.47 % | Val loss 0.6671 | Val acc 79.52%

> Training~ :  69%|███████████████████████████████████████████████████████████████████████████████▎                                   | 138/200 [00:17<00:10,  5.98it/s]

 Epochs 137 | Train loss : 0.70 | Train acc 77.69 % | Val loss 0.6728 | Val acc 79.52%
 Epochs 138 | Train loss : 0.69 | Train acc 75.86 % | Val loss 0.6789 | Val acc 79.52%

> Training~ :  70%|████████████████████████████████████████████████████████████████████████████████▌                                  | 140/200 [00:18<00:10,  5.97it/s]

 Epochs 139 | Train loss : 0.72 | Train acc 76.88 % | Val loss 0.6772 | Val acc 79.52%
 Epochs 140 | Train loss : 0.70 | Train acc 76.47 % | Val loss 0.6779 | Val acc 79.52%

> Training~ :  71%|█████████████████████████████████████████████████████████████████████████████████▋                                 | 142/200 [00:18<00:08,  6.50it/s]

 Epochs 141 | Train loss : 0.68 | Train acc 78.30 % | Val loss 0.6708 | Val acc 79.52%
 Epochs 142 | Train loss : 0.69 | Train acc 76.67 % | Val loss 0.6670 | Val acc 79.52%

> Training~ :  72%|██████████████████████████████████████████████████████████████████████████████████▊                                | 144/200 [00:18<00:07,  7.24it/s]

 Epochs 143 | Train loss : 0.67 | Train acc 77.69 % | Val loss 0.6597 | Val acc 79.52%
 Epochs 144 | Train loss : 0.68 | Train acc 76.67 % | Val loss 0.6539 | Val acc 79.52%

> Training~ :  73%|███████████████████████████████████████████████████████████████████████████████████▉                               | 146/200 [00:18<00:07,  7.41it/s]

 Epochs 145 | Train loss : 0.67 | Train acc 78.70 % | Val loss 0.6594 | Val acc 79.52%
 Epochs 146 | Train loss : 0.68 | Train acc 79.11 % | Val loss 0.6708 | Val acc 79.52%

> Training~ :  74%|█████████████████████████████████████████████████████████████████████████████████████                              | 148/200 [00:19<00:06,  7.74it/s]

 Epochs 147 | Train loss : 0.69 | Train acc 77.89 % | Val loss 0.6467 | Val acc 80.72%
 Epochs 148 | Train loss : 0.68 | Train acc 77.08 % | Val loss 0.6728 | Val acc 79.52%

> Training~ :  75%|██████████████████████████████████████████████████████████████████████████████████████▎                            | 150/200 [00:19<00:06,  7.66it/s]

 Epochs 149 | Train loss : 0.68 | Train acc 77.89 % | Val loss 0.6399 | Val acc 80.72%
 Epochs 150 | Train loss : 0.67 | Train acc 77.28 % | Val loss 0.6484 | Val acc 79.52%

> Training~ :  76%|███████████████████████████████████████████████████████████████████████████████████████▍                           | 152/200 [00:19<00:06,  7.60it/s]

 Epochs 151 | Train loss : 0.67 | Train acc 77.48 % | Val loss 0.6656 | Val acc 79.52%
 Epochs 152 | Train loss : 0.66 | Train acc 79.11 % | Val loss 0.6432 | Val acc 80.72%

> Training~ :  77%|████████████████████████████████████████████████████████████████████████████████████████▌                          | 154/200 [00:20<00:05,  7.77it/s]

 Epochs 153 | Train loss : 0.68 | Train acc 77.69 % | Val loss 0.6519 | Val acc 79.52%
 Epochs 154 | Train loss : 0.67 | Train acc 77.89 % | Val loss 0.6390 | Val acc 80.72%

> Training~ :  78%|█████████████████████████████████████████████████████████████████████████████████████████▋                         | 156/200 [00:20<00:05,  7.55it/s]

 Epochs 155 | Train loss : 0.68 | Train acc 78.50 % | Val loss 0.6588 | Val acc 79.52%
 Epochs 156 | Train loss : 0.66 | Train acc 79.51 % | Val loss 0.6318 | Val acc 80.72%

> Training~ :  79%|██████████████████████████████████████████████████████████████████████████████████████████▊                        | 158/200 [00:20<00:05,  7.14it/s]

 Epochs 157 | Train loss : 0.65 | Train acc 79.72 % | Val loss 0.6465 | Val acc 79.52%
 Epochs 158 | Train loss : 0.68 | Train acc 77.89 % | Val loss 0.6377 | Val acc 80.72%

> Training~ :  80%|████████████████████████████████████████████████████████████████████████████████████████████                       | 160/200 [00:20<00:05,  7.61it/s]

 Epochs 159 | Train loss : 0.65 | Train acc 81.34 % | Val loss 0.6401 | Val acc 79.52%
 Epochs 160 | Train loss : 0.66 | Train acc 77.28 % | Val loss 0.6486 | Val acc 79.52%

> Training~ :  81%|█████████████████████████████████████████████████████████████████████████████████████████████▏                     | 162/200 [00:21<00:04,  7.89it/s]

 Epochs 161 | Train loss : 0.65 | Train acc 78.30 % | Val loss 0.6419 | Val acc 80.72%
 Epochs 162 | Train loss : 0.66 | Train acc 78.70 % | Val loss 0.6481 | Val acc 78.31%

> Training~ :  82%|██████████████████████████████████████████████████████████████████████████████████████████████▎                    | 164/200 [00:21<00:04,  7.86it/s]

 Epochs 163 | Train loss : 0.65 | Train acc 79.11 % | Val loss 0.6254 | Val acc 80.72%
 Epochs 164 | Train loss : 0.64 | Train acc 78.50 % | Val loss 0.6185 | Val acc 80.72%

> Training~ :  83%|███████████████████████████████████████████████████████████████████████████████████████████████▍                   | 166/200 [00:21<00:04,  7.82it/s]

 Epochs 165 | Train loss : 0.65 | Train acc 77.69 % | Val loss 0.6237 | Val acc 80.72%
 Epochs 166 | Train loss : 0.64 | Train acc 79.31 % | Val loss 0.6218 | Val acc 80.72%

> Training~ :  84%|████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 168/200 [00:21<00:04,  7.56it/s]

 Epochs 167 | Train loss : 0.63 | Train acc 79.92 % | Val loss 0.6230 | Val acc 80.72%
 Epochs 168 | Train loss : 0.63 | Train acc 79.72 % | Val loss 0.6240 | Val acc 80.72%

> Training~ :  85%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 170/200 [00:22<00:04,  7.23it/s]

 Epochs 169 | Train loss : 0.63 | Train acc 78.90 % | Val loss 0.6129 | Val acc 80.72%
 Epochs 170 | Train loss : 0.62 | Train acc 80.73 % | Val loss 0.6196 | Val acc 80.72%

> Training~ :  86%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                | 172/200 [00:22<00:03,  7.46it/s]

 Epochs 171 | Train loss : 0.62 | Train acc 80.53 % | Val loss 0.6086 | Val acc 80.72%
 Epochs 172 | Train loss : 0.64 | Train acc 79.11 % | Val loss 0.6096 | Val acc 79.52%

> Training~ :  87%|████████████████████████████████████████████████████████████████████████████████████████████████████               | 174/200 [00:22<00:03,  7.74it/s]

 Epochs 173 | Train loss : 0.62 | Train acc 80.32 % | Val loss 0.6123 | Val acc 79.52%
 Epochs 174 | Train loss : 0.65 | Train acc 78.30 % | Val loss 0.6214 | Val acc 79.52%

> Training~ :  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 176/200 [00:22<00:03,  7.83it/s]

 Epochs 175 | Train loss : 0.61 | Train acc 80.73 % | Val loss 0.6010 | Val acc 80.72%
 Epochs 176 | Train loss : 0.61 | Train acc 82.76 % | Val loss 0.6070 | Val acc 80.72%

> Training~ :  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 178/200 [00:23<00:02,  7.79it/s]

 Epochs 177 | Train loss : 0.60 | Train acc 81.34 % | Val loss 0.6073 | Val acc 79.52%
 Epochs 178 | Train loss : 0.63 | Train acc 80.12 % | Val loss 0.5985 | Val acc 79.52%

> Training~ :  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 180/200 [00:23<00:02,  8.11it/s]

 Epochs 179 | Train loss : 0.62 | Train acc 80.32 % | Val loss 0.6085 | Val acc 79.52%
 Epochs 180 | Train loss : 0.61 | Train acc 81.95 % | Val loss 0.6012 | Val acc 80.72%

> Training~ :  91%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 182/200 [00:23<00:02,  7.13it/s]

 Epochs 181 | Train loss : 0.61 | Train acc 80.53 % | Val loss 0.6008 | Val acc 80.72%
 Epochs 182 | Train loss : 0.60 | Train acc 82.15 % | Val loss 0.5828 | Val acc 80.72%

> Training~ :  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 184/200 [00:24<00:02,  6.63it/s]

 Epochs 183 | Train loss : 0.61 | Train acc 80.12 % | Val loss 0.5876 | Val acc 80.72%
 Epochs 184 | Train loss : 0.59 | Train acc 79.31 % | Val loss 0.5920 | Val acc 79.52%

> Training~ :  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 186/200 [00:24<00:02,  6.66it/s]

 Epochs 185 | Train loss : 0.60 | Train acc 80.32 % | Val loss 0.5955 | Val acc 79.52%
 Epochs 186 | Train loss : 0.60 | Train acc 80.12 % | Val loss 0.5911 | Val acc 79.52%

> Training~ :  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 188/200 [00:24<00:01,  6.80it/s]

 Epochs 187 | Train loss : 0.61 | Train acc 80.53 % | Val loss 0.5849 | Val acc 79.52%
 Epochs 188 | Train loss : 0.60 | Train acc 81.14 % | Val loss 0.5986 | Val acc 79.52%

> Training~ :  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 190/200 [00:24<00:01,  7.38it/s]

 Epochs 189 | Train loss : 0.60 | Train acc 79.92 % | Val loss 0.5877 | Val acc 80.72%
 Epochs 190 | Train loss : 0.60 | Train acc 80.93 % | Val loss 0.5849 | Val acc 80.72%

> Training~ :  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 192/200 [00:25<00:01,  6.90it/s]

 Epochs 191 | Train loss : 0.60 | Train acc 80.73 % | Val loss 0.5829 | Val acc 80.72%
 Epochs 192 | Train loss : 0.59 | Train acc 79.92 % | Val loss 0.5886 | Val acc 79.52%

> Training~ :  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 194/200 [00:25<00:00,  6.93it/s]

 Epochs 193 | Train loss : 0.58 | Train acc 80.73 % | Val loss 0.5681 | Val acc 80.72%
 Epochs 194 | Train loss : 0.58 | Train acc 81.14 % | Val loss 0.5626 | Val acc 80.72%

> Training~ :  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 196/200 [00:25<00:00,  7.58it/s]

 Epochs 195 | Train loss : 0.59 | Train acc 80.53 % | Val loss 0.5765 | Val acc 79.52%
 Epochs 196 | Train loss : 0.56 | Train acc 81.95 % | Val loss 0.5650 | Val acc 80.72%

> Training~ :  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 198/200 [00:25<00:00,  7.85it/s]

 Epochs 197 | Train loss : 0.59 | Train acc 79.11 % | Val loss 0.5664 | Val acc 80.72%
 Epochs 198 | Train loss : 0.57 | Train acc 81.14 % | Val loss 0.5630 | Val acc 80.72%

> Training~ : 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:26<00:00,  7.61it/s]

 Epochs 199 | Train loss : 0.57 | Train acc 81.34 % | Val loss 0.5580 | Val acc 80.72%
 Epochs 200 | Train loss : 0.57 | Train acc 81.54 % | Val loss 0.5510 | Val acc 80.72%

=> Final Test accuracy: 82.61%